# Generated by Django 4.0.4 on 2022-05-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='num_reviews',
            new_name='reviews',
        ),
    ]
