# Generated by Django 4.0.4 on 2022-05-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_num_reviews_profile_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reviews',
            new_name='num_reviews',
        ),
    ]
